/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package se.jherrlin.bomberman.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Counter extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3362701954532226463L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Counter\",\"namespace\":\"se.jherrlin.bomberman.models\",\"fields\":[{\"name\":\"count\",\"type\":\"int\",\"doc\":\"Counts\"},{\"name\":\"latest\",\"type\":\"string\",\"doc\":\"Datetime when latest event came by\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Counter> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Counter> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Counter> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Counter> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Counter> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Counter to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Counter from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Counter instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Counter fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Counts */
  private int count;
  /** Datetime when latest event came by */
  private java.lang.CharSequence latest;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Counter() {}

  /**
   * All-args constructor.
   * @param count Counts
   * @param latest Datetime when latest event came by
   */
  public Counter(java.lang.Integer count, java.lang.CharSequence latest) {
    this.count = count;
    this.latest = latest;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return latest;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: count = (java.lang.Integer)value$; break;
    case 1: latest = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'count' field.
   * @return Counts
   */
  public int getCount() {
    return count;
  }


  /**
   * Sets the value of the 'count' field.
   * Counts
   * @param value the value to set.
   */
  public void setCount(int value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'latest' field.
   * @return Datetime when latest event came by
   */
  public java.lang.CharSequence getLatest() {
    return latest;
  }


  /**
   * Sets the value of the 'latest' field.
   * Datetime when latest event came by
   * @param value the value to set.
   */
  public void setLatest(java.lang.CharSequence value) {
    this.latest = value;
  }

  /**
   * Creates a new Counter RecordBuilder.
   * @return A new Counter RecordBuilder
   */
  public static se.jherrlin.bomberman.models.Counter.Builder newBuilder() {
    return new se.jherrlin.bomberman.models.Counter.Builder();
  }

  /**
   * Creates a new Counter RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Counter RecordBuilder
   */
  public static se.jherrlin.bomberman.models.Counter.Builder newBuilder(se.jherrlin.bomberman.models.Counter.Builder other) {
    if (other == null) {
      return new se.jherrlin.bomberman.models.Counter.Builder();
    } else {
      return new se.jherrlin.bomberman.models.Counter.Builder(other);
    }
  }

  /**
   * Creates a new Counter RecordBuilder by copying an existing Counter instance.
   * @param other The existing instance to copy.
   * @return A new Counter RecordBuilder
   */
  public static se.jherrlin.bomberman.models.Counter.Builder newBuilder(se.jherrlin.bomberman.models.Counter other) {
    if (other == null) {
      return new se.jherrlin.bomberman.models.Counter.Builder();
    } else {
      return new se.jherrlin.bomberman.models.Counter.Builder(other);
    }
  }

  /**
   * RecordBuilder for Counter instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Counter>
    implements org.apache.avro.data.RecordBuilder<Counter> {

    /** Counts */
    private int count;
    /** Datetime when latest event came by */
    private java.lang.CharSequence latest;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(se.jherrlin.bomberman.models.Counter.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.latest)) {
        this.latest = data().deepCopy(fields()[1].schema(), other.latest);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Counter instance
     * @param other The existing instance to copy.
     */
    private Builder(se.jherrlin.bomberman.models.Counter other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latest)) {
        this.latest = data().deepCopy(fields()[1].schema(), other.latest);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'count' field.
      * Counts
      * @return The value.
      */
    public int getCount() {
      return count;
    }


    /**
      * Sets the value of the 'count' field.
      * Counts
      * @param value The value of 'count'.
      * @return This builder.
      */
    public se.jherrlin.bomberman.models.Counter.Builder setCount(int value) {
      validate(fields()[0], value);
      this.count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * Counts
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'count' field.
      * Counts
      * @return This builder.
      */
    public se.jherrlin.bomberman.models.Counter.Builder clearCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'latest' field.
      * Datetime when latest event came by
      * @return The value.
      */
    public java.lang.CharSequence getLatest() {
      return latest;
    }


    /**
      * Sets the value of the 'latest' field.
      * Datetime when latest event came by
      * @param value The value of 'latest'.
      * @return This builder.
      */
    public se.jherrlin.bomberman.models.Counter.Builder setLatest(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.latest = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'latest' field has been set.
      * Datetime when latest event came by
      * @return True if the 'latest' field has been set, false otherwise.
      */
    public boolean hasLatest() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'latest' field.
      * Datetime when latest event came by
      * @return This builder.
      */
    public se.jherrlin.bomberman.models.Counter.Builder clearLatest() {
      latest = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Counter build() {
      try {
        Counter record = new Counter();
        record.count = fieldSetFlags()[0] ? this.count : (java.lang.Integer) defaultValue(fields()[0]);
        record.latest = fieldSetFlags()[1] ? this.latest : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Counter>
    WRITER$ = (org.apache.avro.io.DatumWriter<Counter>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Counter>
    READER$ = (org.apache.avro.io.DatumReader<Counter>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.count);

    out.writeString(this.latest);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.count = in.readInt();

      this.latest = in.readString(this.latest instanceof Utf8 ? (Utf8)this.latest : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.count = in.readInt();
          break;

        case 1:
          this.latest = in.readString(this.latest instanceof Utf8 ? (Utf8)this.latest : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










